apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-2
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: fluxcd-2022
  url: https://github.com/patelronak66/k8s-fluxcd
  secretRef:
    name: example-app-2-github